GetandTake/Models/Product.cs
using GetandTake.Core.Models;

namespace GetandTake.Models;

public class Product : BaseEntity
{
    public int ProductID { get; set; }

    public string ProductName { get; set; }

    public string QuantityPerUnit { get; set; }

    public decimal? UnitPrice { get; set; }

    public short? UnitsInStock { get; set; }

    public short? UnitsOnOrder { get; set; }

    public short? ReorderLevel { get; set; }

    public bool Discontinued { get; set; }

    public int? SupplierID { get; set; }

    public int? CategoryID { get; set; }

    public Supplier Supplier { get; set; }

    public Category Category { get; set; }
}

GetandTake/Pages/Categories/Edit.cshtml.cs
using AutoMapper;
using GetandTake.Business.Services.Abstract;
using GetandTake.Models.DTOs.DetailDTO;
using GetandTake.Models.DTOs.ResponseDTO;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using SmartBreadcrumbs.Attributes;

namespace GetandTake.Pages.Categories;

[Breadcrumb("Edit Category", FromPage = typeof(CategoryModel))]
public class EditModel : PageModel
{
    private readonly ICategoryService _categoryService;
    private readonly IMapper _mapper;

    [BindProperty]
    public CategoryResponse Category { get; set; }

    public EditModel(
        ICategoryService categoryService,
        IMapper mapper)
    {
        _categoryService = categoryService;
        _mapper = mapper;
    } 

    public async Task OnGet(int id)
    {
        Category = await _categoryService.GetByIdAsync(id);
    }

    public async Task<IActionResult> OnPost(int id)
    {
        if (!ModelState.IsValid)
        {
            return Page();
        }

        var category = _mapper.Map<CategoryDetail>(Category);
        await _categoryService.UpdateAsync(id, category);

        return RedirectToPage("Category");
    }
}

GetandTake/Pages/Products/Create.cshtml.cs
using GetandTake.Business.Services.Abstract;
using GetandTake.Models;
using GetandTake.Models.DTOs.DetailDTO;
using GetandTake.Models.DTOs.ResponseDTO;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using SmartBreadcrumbs.Attributes;

namespace GetandTake.Pages.Products;

[Breadcrumb("Create Product", FromPage = typeof(ProductModel))]
public class CreateModel : PageModel
{
    private readonly IProductService _productService;
    private readonly ICategoryService _categoryService;
    private readonly ISupplierService _supplierService;

    public IEnumerable<CategoryResponse> Categories { get; private set; }

    public IEnumerable<Supplier> Suppliers { get; private set; }

    [BindProperty]
    public ProductDetail ProductDTO { get; set; }

    public CreateModel(
        IProductService productService,
        ICategoryService categoryService,
        ISupplierService supplierService)
    {
        _productService = productService;
        _categoryService = categoryService;
        _supplierService = supplierService;
    }

    public async Task OnGetAsync()
    {
        Categories = await _categoryService.GetAllAsync();
        Suppliers = await _supplierService.GetAllAsync();
    }

    public async Task<IActionResult> OnPostCreateAsync()
    {
        if (!ModelState.IsValid)
        {
            return Page();
        }
        await _productService.CreateAsync(ProductDTO);

        return RedirectToPage("Product");
    }
}

GetandTake/Pages/Products/Edit.cshtml.cs
using GetandTake.Business.Services.Abstract;
using GetandTake.Models;
using GetandTake.Models.DTOs.DetailDTO;
using GetandTake.Models.DTOs.ResponseDTO;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using SmartBreadcrumbs.Attributes;

namespace GetandTake.Pages.Products;

[Breadcrumb("Edit Product", FromPage = typeof(ProductModel))]
public class EditModel : PageModel
{
    private readonly IProductService _productService;
    private readonly ICategoryService _categoryService;
    private readonly ISupplierService _supplierService;

    public ProductResponse ProductDTO { get; set; }

    [BindProperty]
    public ProductDetail Product { get; set; }

    public IEnumerable<CategoryResponse> Categories { get; private set; }

    public IEnumerable<Supplier> Suppliers { get; private set; }

    public EditModel(
        IProductService productService,
        ICategoryService categoryService,
        ISupplierService supplierService)
    {
        _productService = productService;
        _categoryService = categoryService;
        _supplierService = supplierService;
    }

    public async Task OnGet(int id)
    {
        ProductDTO = await _productService.GetByIdAsync(id);
        Categories = await _categoryService.GetAllAsync();
        Suppliers = await _supplierService.GetAllAsync();
    }

    public async Task<IActionResult> OnPost(int id)
    {
        if (!ModelState.IsValid)
        {
            return Page();
        }
        await _productService.UpdateAsync(id, Product);

        return RedirectToPage("Product");
    }
}

GetandTake/Pages/Products/Product.cshtml.cs
using GetandTake.Business.Services.Abstract;
using GetandTake.Configuration.Settings;
using GetandTake.Models.DTOs.ResponseDTO;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc.RazorPages;
using SmartBreadcrumbs.Attributes;

namespace GetandTake.Pages.Products;

[AllowAnonymous]
[Breadcrumb("Products", FromPage = typeof(IndexModel))]
public class ProductModel : PageModel
{
    private readonly IProductService _productService;
    private readonly AppSettings _appSettings;
    private readonly ILogger _logger;

    public IEnumerable<ProductResponse> Products { get; private set; }

    public int AmountOfProduct { get; private set; }

    public ProductModel
        (
        IProductService productService,
        AppSettings appSettings,
        ILogger<ProductModel> logger
        )
    {
        _productService = productService;
        _appSettings = appSettings;
        _logger = logger;
    }

    public async Task OnGet()
    {
        _logger.LogInformation("Products process start at {DT}",
            DateTime.UtcNow.ToLongTimeString());

        AmountOfProduct = _appSettings.Products.MaximumAmount;
        Products = await _productService.GetByMaxAmountOfAsync(AmountOfProduct);
    }
}

GetandTake/ViewComponents/ProductViewComponent.cs
using GetandTake.Business.Services.Abstract;
using Microsoft.AspNetCore.Mvc;

namespace GetandTake.ViewComponents;

public class ProductViewComponent : ViewComponent
{
    private readonly IProductService _productService;

    public ProductViewComponent(IProductService productService)
    {
        _productService = productService;
    }

    public async Task<IViewComponentResult> InvokeAsync()
    {
        var products = await _productService.GetAllAsync();

        return View(products);
    }
}

GetandTake/Pages/Products/Create.cshtml
@page
@model GetandTake.Pages.Products.CreateModel
@{
    ViewData["Title"] = "Create a Product";
}

@if (!ModelState.IsValid)
{
    <div class="col-md-offset-2 col-md-10">
        <h3 class="text-danger">Validation Errors</h3>
        <div asp-validation-summary="All"></div>
    </div>
}

<form method="post">
    <div class="border p-3 mt-4">
        <div class="mb-2">
            <label asp-for="ProductDTO.ProductName" class="col-sm-2 col-form-label">Product Name</label>
            <input type="text" asp-for="ProductDTO.ProductName" class="form-control" required/>
            <span asp-validation-for="ProductDTO.ProductName" class="text-danger"></span>
        </div>
        <div class="mb-2">
            <label asp-for="ProductDTO.QuantityPerUnit" class="col-sm-2 col-form-label">QuantityPerUnit:</label>
            <input type="text" asp-for="ProductDTO.QuantityPerUnit" class="form-control" />
            <span asp-validation-for="ProductDTO.QuantityPerUnit" class="text-danger"></span>
        </div>
        <div class="mb-2">
            <label asp-for="ProductDTO.UnitPrice" class="col-sm-2 col-form-label">Unit Price</label>
            <input type="text" asp-for="ProductDTO.UnitPrice" class="form-control" />
            <span asp-validation-for="ProductDTO.UnitPrice" class="text-danger"></span>
        </div>
        <div class="mb-2">
            <label asp-for="ProductDTO.UnitsInStock" class="col-sm-2 col-form-label">Units in Stock</label>
            <input type="text" asp-for="ProductDTO.UnitsInStock" class="form-control"/>
            <span asp-validation-for="ProductDTO.UnitsInStock" class="text-danger"></span>
        </div>
        <div class="mb-2">
            <label asp-for="ProductDTO.UnitsOnOrder" class="col-sm-2 col-form-label">Units OnOrder </label>
            <input type="text" asp-for="ProductDTO.UnitsOnOrder" class="form-control" />
            <span asp-validation-for="ProductDTO.UnitsOnOrder" class="text-danger"></span>
        </div>
        <div class="mb-2">
            <label asp-for="ProductDTO.ReorderLevel" class="col-sm-2 col-form-label">Reorder Level</label>
            <input type="text" asp-for="ProductDTO.ReorderLevel" class="form-control" />
            <span asp-validation-for="ProductDTO.ReorderLevel" class="text-danger"></span>
        </div>
        <div class="mb-2">
            <label asp-for="ProductDTO.Discontinued" class="col-sm-2 col-form-label">Discontinued</label>
            <input type="checkbox" asp-for="ProductDTO.Discontinued" />
            <span asp-validation-for="ProductDTO.Discontinued" class="text-danger"></span>
        </div>
        <div class="mb-2">
            <label asp-for="ProductDTO.CategoryId" class="col-sm-2 col-form-label">Category</label>
            <select asp-for="ProductDTO.CategoryId" class="form-select">
                <option selected></option>

                @foreach (var category in Model.Categories)
                {
                    <option value="@category.CategoryID">@category.CategoryName</option>
                }

            </select>
        </div>
        <div class="mb-2">
            <label asp-for="ProductDTO.SupplierId" class="col-sm-2 col-form-label">Supplier</label>
            <select asp-for="ProductDTO.SupplierId" class="form-select">
                <option selected></option>

                @foreach (var supplier in Model.Suppliers)
                {
                    <option value="@supplier.SupplierID">@supplier.CompanyName</option>
                }

            </select>
        </div>
        <button type="submit" asp-page-handler="Create" class="btn btn-success">Create</button>
    </div>
</form>

GetandTake/Pages/Products/Edit.cshtml
@page
@model GetandTake.Pages.Products.EditModel
@{
    ViewData["Title"] = "Edit Product";
}

@if (!ModelState.IsValid)
{
    <div class="col-md-offset-2 col-md-10">
        <h3 class="text-danger">Validation Errors</h3>
        <div asp-validation-summary="All"></div>
    </div>
}

<div class="container">
    <div class="row">
        <div class="col-4">
            <div class="border p-3 mt-4">
                <input type="text" disabled asp-for="ProductDTO.ProductID" />
                <hr />
                <label asp-for="Product.ProductName">Product Name</label>
                <input type="text" disabled asp-for="ProductDTO.ProductName" />
                <hr />
                <label asp-for="Product.QuantityPerUnit">QuantityPerUnit:</label>
                <input type="text" disabled asp-for="ProductDTO.QuantityPerUnit" />
                <hr />
                <label asp-for="Product.QuantityPerUnit">UnitPrice:</label>
                <input type="text" disabled asp-for="ProductDTO.UnitPrice" />
                <hr />
                <label asp-for="Product.QuantityPerUnit">UnitsInStock:</label>
                <input type="text" disabled asp-for="ProductDTO.UnitsInStock" />
                <hr />
                <label asp-for="Product.QuantityPerUnit">UnitsOnOrder:</label>
                <input type="text" disabled asp-for="ProductDTO.UnitsOnOrder" />
                <hr />
                <label asp-for="Product.QuantityPerUnit">ReorderLevel:</label>
                <input type="text" disabled asp-for="ProductDTO.ReorderLevel" />
                <hr />
                <label asp-for="Product.QuantityPerUnit">Discontinued:</label>
                <input type="text" disabled asp-for="ProductDTO.Discontinued" />
                <hr />
                <label asp-for="Product.QuantityPerUnit">Category:</label>
                <input type="text" disabled asp-for="ProductDTO.Category" />
                <hr />
                <label asp-for="Product.QuantityPerUnit">Supplier:</label>
                <input type="text" disabled asp-for="ProductDTO.Supplier" />
            </div>
        </div>
        <div class="col-8">
            <form method="post">
                <div class="border p-3 mt-4">
                    <div class="row pb-2">
                        <h4 class="text-success pl-3">
                            Fill Product Details and Edit
                        </h4>
                        <hr />
                    </div>
                    <div asp-validation-summary="All"></div>
                    <div class="mb-2">
                        <label asp-for="Product.ProductName" class="col-sm-2 col-form-label">Product Name</label>
                        <input type="text" asp-for="Product.ProductName" class="form-control" />
                        <span asp-validation-for="Product.ProductName" class="text-danger"></span>
                    </div>
                    <div class="mb-2">
                        <label asp-for="Product.QuantityPerUnit" class="col-sm-2 col-form-label">QuantityPerUnit:</label>
                        <input type="text" asp-for="Product.QuantityPerUnit" class="form-control" />
                        <span class="text-danger field-validation-valid" asp-validation-for="Product.QuantityPerUnit"></span>
                    </div>
                    <div class="mb-2">
                        <label asp-for="Product.UnitPrice" class="col-sm-2 col-form-label">Unit Price</label>
                        <input type="text" asp-for="Product.UnitPrice" class="form-control" />
                        <span asp-validation-for="Product.UnitPrice" class="text-danger"></span>
                    </div>
                    <div class="mb-2">
                        <label asp-for="Product.UnitsInStock" class="col-sm-2 col-form-label">Units in Stock</label>
                        <input type="text" asp-for="Product.UnitsInStock" class="form-control" />
                        <span asp-validation-for="Product.UnitsInStock" class="text-danger"></span>
                    </div>
                    <div class="mb-2">
                        <label asp-for="Product.UnitsOnOrder" class="col-sm-2 col-form-label">Units OnOrder </label>
                        <input type="text" asp-for="Product.UnitsOnOrder" class="form-control" />
                        <span asp-validation-for="Product.UnitsOnOrder" class="text-danger"></span>
                    </div>
                    <div class="mb-2">
                        <label asp-for="Product.ReorderLevel" class="col-sm-2 col-form-label">Reorder Level</label>
                        <input type="text" asp-for="Product.ReorderLevel" class="form-control" />
                        <span asp-validation-for="Product.ReorderLevel" class="text-danger"></span>
                    </div>
                    <div class="mb-2">
                        <label asp-for="Product.Discontinued" class="col-sm-2 col-form-label">Discontinued</label>
                        <input type="checkbox" asp-for="Product.Discontinued"/>
                        <span asp-validation-for="Product.Discontinued" class="text-danger"></span>
                    </div>
                    <div class="mb-2">
                        <label asp-for="Product.CategoryId" class="col-sm-2 col-form-label">Category</label>
                        <select asp-for="Product.CategoryId" class="form-select">
                            <option selected disabled>@Model.ProductDTO.Category</option>
                            @foreach (var category in Model.Categories)
                            {
                                <option value="@category.CategoryID">@category.CategoryName</option>
                            }
                        </select>
                    </div>
                    <div class="mb-2">
                        <label asp-for="Product.SupplierId" class="col-sm-2 col-form-label">Supplier</label>
                        <select asp-for="Product.SupplierId" class="form-select">
                            <option selected disabled>@Model.ProductDTO.Supplier</option>
                            @foreach (var supplier in Model.Suppliers)
                            {
                                <option value="@supplier.SupplierID">@supplier.CompanyName</option>
                            }
                        </select>
                    </div>
                    <button type="submit" asp-page-handler="Update" class="btn btn-success">Edit</button>
                </div>
            </form>
        </div>
    </div>
</div>

GetandTake/Pages/Products/Product.cshtml
@page
@using GetandTake.ViewComponents
@model GetandTake.Pages.Products.ProductModel

@section Title
{
    <h5 class="title">Products</h5>
}

<div class="col-md-3">
    @await  Component.InvokeAsync("Product")
</div>